version: '3.8'

services:
  langfuse:
    image: langfuse/langfuse:2
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://langfuse:langfuse@postgres:5432/langfuse
      - ENCRYPTION_KEY=7f43916bf34047925b49a850cafef51d8df8840c3c5a05926f8482268524566c  # random 64 character string
      - SALT=2xqyIpXpdu3l5szwrWAyWhQuFT9qcRxvcA77hRCpaEw=  # random 64 character string
      - NEXTAUTH_SECRET=ytUgfYu9Rlz0VqE6LfEPvwyRfFnimGylo8zhlT2337I=  # random 64 character string
      - NEXTAUTH_URL=http://localhost:3000
      - TELEMETRY_ENABLED=${TELEMETRY_ENABLED:-true}
      - LANGFUSE_ENABLE_EXPERIMENTAL_FEATURES=${LANGFUSE_ENABLE_EXPERIMENTAL_FEATURES:-false}
    depends_on:
      - postgres

  postgres:
    image: postgres:14
    environment:
      - POSTGRES_USER=langfuse
      - POSTGRES_PASSWORD=langfuse
      - POSTGRES_DB=langfuse
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: